




/*
     FILE ARCHIVED ON 10:36:38 Dec 29, 2012 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 19:54:49 Feb 18, 2021.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
(function(){var b=!0,h=null,l=!1,n,p=this;function q(a){a=a.split(".");for(var c=p,d;d=a.shift();)if(c[d]!=h)c=c[d];else return h;return c}
function aa(a){var c=typeof a;if("object"==c)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return c;var d=Object.prototype.toString.call(a);if("[object Window]"==d)return"object";if("[object Array]"==d||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==d||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof a.call)return"object";return c}function s(a){return"string"==typeof a}Math.floor(2147483648*Math.random()).toString(36);var ba=Date.now||function(){return+new Date};function t(a,c){var d=a.split("."),e=p;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var f;d.length&&(f=d.shift());)!d.length&&void 0!==c?e[f]=c:e=e[f]?e[f]:e[f]={}};var u={$:l,U:{"url-identifier":"?spf=1","link-class":"spf-link","nolink-class":h,"request-timeout":4E3,"cache-lifetime":6E4,"navigate-started-callback":h,"navigate-history-callback":h,"navigate-received-callback":h,"navigate-processed-callback":h,"load-received-callback":h,"load-processed-callback":h,"transition-class":"spf-transition","transition-duration":425,"transition-forward-parent-class":"spf-transition-forward","transition-reverse-parent-class":"spf-transition-reverse","transition-current-child-class":"spf-current",
"transition-forward-child-class":"spf-forward","transition-reverse-child-class":"spf-reverse"},config:{}};u.now=Date.now||function(){return+new Date};u.getKey=function(a){return a["spf-key"]||(a["spf-key"]=u.now()+"-"+ ++u.wa)};u.wa=0;u.debug={};u.debug.debug=function(a){u.debug.log("debug",arguments)};u.debug.info=function(a){u.debug.log("info",arguments)};u.debug.warn=function(a){u.debug.log("warn",arguments)};u.debug.error=function(a){u.debug.log("error",arguments)};
u.debug.log=function(a,c){if(u.$&&window.console){c=Array.prototype.slice.call(c,0);var d=u.now(),e=d-u.debug.va;"debug"==a&&c.unshift("  >  "+e+"ms: ");if(u.debug.ua){d="spf_debug_"+d;window[d]=c;for(var e="window.console."+a+"(",f=0,g=c.length;f<g;f++)e+=0<f?",":"",e+=d+"["+f+"]";eval("("+(e+")")+")")}else window.console.log(a+": "+c.join(" "))}};u.debug.va=u.now();u.debug.ua=!(!window.console||eval("/*@cc_on!@*/false"));u.history={};function v(a){this.w=a;this.e=0;this.j=window.location.href;var c=this;this.C=function(){c.O.apply(c,arguments)}}
v.prototype.O=function(a){var c=window.location.href;u.debug.info("spf.history.handlePop: ","url=",c,"evt=",a);u.debug.debug("new url: ",c!=this.j);u.debug.debug("current timestamp: ",this.e);if(a.state)if(a=a.state,c==this.j)this.e=a["spf-timestamp"],u.debug.debug("replace: ","url=",c,"state=",a),window.history.replaceState(a,"",c);else{var d=a["spf-timestamp"];a["spf-back"]=!!(d<this.e);this.e=d;u.debug.debug("callback: ","url=",c,"state=",a);this.j=c;this.w(c,a)}};
v.prototype.add=function(a,c,d){u.debug.info("spf.history.add: ","url=",a,"state=",c);w(this,l,a,c,d)};v.prototype.replace=function(a,c,d){u.debug.info("spf.history.replace: ","url=",a,"state=",c);w(this,b,a,c,d)};function w(a,c,d,e,f){if(d||e)d=d||window.location.href,e=e||{},a.e=u.now(),e["spf-timestamp"]=a.e,c?window.history.replaceState(e,"",d):window.history.pushState(e,"",d),u.debug.debug("entry:  ","url=",d,"state=",e),a.j=d,f||a.w(d,e)};u.history.init=function(a){u.history.o||(u.history.K||(u.history.K=new v(a)),a=u.history.K,a.j=window.location.href,a.replace(a.j,h,b),window.addEventListener("popstate",a.C,l),u.history.o=b)};u.history.p=function(){u.history.o&&(window.removeEventListener("popstate",u.history.K.C,l),u.history.o=l)};u.history.add=function(a,c,d){u.history.K.add(a,c,d)};u.history.o=l;u.i={};u.i.get=function(a){if(u.i.t&&a in u.i.t){var c=u.i.t[a],d=u.now()-c.j;if(isNaN(c.e)||d<c.e)return c.data;u.i.remove(a)}};u.i.set=function(a,c,d){u.i.t||(u.i.t={});d=parseInt(d,10);0>=d||(u.i.t[a]=new ca(c,d))};u.i.remove=function(a){u.i.t&&a in u.i.t&&delete u.i.t[a]};function ca(a,c){this.data=a;this.e=c;this.j=u.now()};u.d={};u.d.k={};u.d.k.get=function(a){return a.className&&a.className.match(/\S+/g)||[]};u.d.k.has=Array.prototype.indexOf?function(a,c){var d=u.d.k.get(a);return-1!=Array.prototype.indexOf.call(d,c)}:function(a,c){for(var d=u.d.k.get(a),e=0,f=d.length;e<f;e++)if(d[e]==c)return b;return l};u.d.k.add=function(a,c){u.d.k.has(a,c)||(a.className+=" "+c)};
u.d.k.remove=Array.prototype.filter?function(a,c){var d=u.d.k.get(a),d=Array.prototype.filter.call(d,function(a){return a!=c});a.className=d.join(" ")}:function(a,c){for(var d=u.d.k.get(a),e=[],f=0,g=d.length;f<g;f++)d[f]!=c&&e.push(d[f]);a.className=e.join(" ")};u.d.fa=function(a,c){c.parentNode.insertBefore(a,c)};u.d.ea=function(a,c){c.parentNode.insertBefore(a,c.nextSibling)};u.d.ca=function(a){var c,d=a.parentNode;if(d&&11!=d.nodeType)if(a.removeNode)a.removeNode(l);else{for(;c=a.firstChild;)d.insertBefore(c,a);d.removeChild(a)}};u.d.da=function(a,c){if(c){for(var d;d=a.firstChild;)c.appendChild(d);a.appendChild(c)}};u.d.W=function(a,c){for(;a;){if(c(a))return a;a=a.parentNode}return h};u.d.dataset={};u.d.dataset.get=function(a,c){return a.dataset?a.dataset[c]:a.getAttribute("data-"+u.h.Z(c))};u.d.dataset.set=function(a,c,d){a.dataset?a.dataset[c]=d:a.setAttribute("data-"+u.h.Z(c),d)};u.pubsub={};u.pubsub.G=function(a,c,d){a in u.pubsub.g||(u.pubsub.g[a]=[]);u.pubsub.g[a].push([c,d])};u.pubsub.ya=function(a,c,d){if(a in u.pubsub.g){a=u.pubsub.g[a];for(var e=0,f=a.length;e<f;e++)if(a[e]&&a[e][0]==c&&a[e][1]==d){a[e]=h;break}}};u.pubsub.q=function(a,c){if(a in u.pubsub.g)for(var d=u.pubsub.g[a],e=Array.prototype.slice.call(arguments,1),f=0,g=d.length;f<g;f++)d[f]&&d[f][0].apply(d[f][1],e)};u.pubsub.clear=function(a){a?a in u.pubsub.g&&delete u.pubsub.g[a]:u.pubsub.g={}};
u.pubsub.g={};u.h={};u.h.contains=function(a,c){return-1!=a.indexOf(c)};u.h.ka=function(a){return 0==a.lastIndexOf("?",0)};u.h.la=function(a){var c=a.length-9;return 0<=c&&a.indexOf("-callback",c)==c};u.h.H=function(a){for(var c=0,d=0,e=a.length;d<e;++d)c=31*c+a.charCodeAt(d),c%=4294967296;return c};u.h.Z=function(a){return String(a).replace(/([A-Z])/g,"-$1").toLowerCase()};u.a={};u.a.scripts={};u.a.scripts.eval=function(a,c){if(window.execScript)window.execScript(a,"JavaScript");else{var d=document.createElement("script");d.appendChild(document.createTextNode(a));var e=document.getElementsByTagName("head")[0];e.insertBefore(d,e.firstChild)}c&&c()};
u.a.scripts.load=function(a,c){var d=u.a.scripts.B+u.h.H(a),e=document.getElementById(d),f=e&&u.d.dataset.get(e,"loaded"),g=e&&!f;if(f)return c&&c(),e;c&&u.pubsub.G(d,c);if(g)return e;var j=u.a.scripts.ha(a,d,function(){u.d.dataset.get(j,"loaded")||(u.d.dataset.set(j,"loaded","true"),u.pubsub.q(d),u.pubsub.clear(d))});return j};
u.a.scripts.ha=function(a,c,d){var e=document.createElement("script");e.id=c;e.onload=function(){setTimeout(d,0)};e.onreadystatechange=function(){switch(e.readyState){case "loaded":case "complete":e.onload()}};e.src=a;a=document.getElementsByTagName("head")[0];a.insertBefore(e,a.firstChild);return e};u.a.scripts.xa=function(a){a=u.a.scripts.B+u.h.H(a);var c=document.getElementById(a);c&&(u.pubsub.clear(a),c.parentNode.removeChild(c))};
u.a.scripts.execute=function(a,c){if(a){var d=[];a=a.replace(u.a.scripts.ra,function(a,c,e){(a=c.match(u.a.scripts.ta))?d.push([a[1],b]):d.push([e,l]);return""});var e=function(){if(0<d.length){var a=d.shift(),g=a[0];a[1]?u.a.scripts.load(g,e):u.a.scripts.eval(g,e)}else c&&c()};e()}else c&&c()};u.a.scripts.B="js-";u.a.scripts.ra=/\x3cscript([\s\S]*?)\x3e([\s\S]*?)\x3c\/script\x3e/ig;u.a.scripts.ta=/src="([\S]+)"/;u.a.styles={};u.a.styles.eval=function(a){var c=document.createElement("style");document.getElementsByTagName("head")[0].appendChild(c);"styleSheet"in c?c.styleSheet.cssText=a:c.appendChild(document.createTextNode(a))};u.a.styles.load=function(a){var c=u.a.styles.B+u.h.H(a),d=document.getElementById(c);if(d)return d;d=document.createElement("link");d.id=c;d.rel="stylesheet";d.href=a;document.getElementsByTagName("head")[0].appendChild(d);return d};
u.a.styles.xa=function(a){(a=document.getElementById(u.a.styles.B+u.h.H(a)))&&a.parentNode.removeChild(a)};u.a.styles.ga=function(a){a&&(a.replace(u.a.styles.oa,function(a,d){if(u.h.contains(d,'rel="stylesheet"')){var e=d.match(u.a.styles.na);e&&u.a.styles.load(e[1])}}),a.replace(u.a.styles.pa,function(a,d,e){e&&u.a.styles.eval(e)}))};u.a.styles.B="css-";u.a.styles.oa=/\x3clink([\s\S]*?)\x3e/ig;u.a.styles.pa=/\x3cstyle([\s\S]*?)\x3e([\s\S]*?)\x3c\/style/ig;u.a.styles.na=/href="([\S]+)"/;u.a.s={};u.a.s.get=function(a,c){return u.a.s.send("GET",a,h,c)};u.a.s.za=function(a,c,d){return u.a.s.send("POST",a,c,d)};
u.a.s.send=function(a,c,d,e){d=e||{};var f=d.ia||function(){},g=d.onError||function(){},j=d.ja||function(){},k,m=u.a.s.create();m.open(a,c,b);var r=m.abort;m.abort=function(){clearTimeout(k);m.onreadystatechange=h;r.call(m)};m.onreadystatechange=function(){if(4==m.readyState)switch(clearTimeout(k),m.status){case 200:case 204:case 304:f(m);break;default:g(m)}};0<d.T&&(k=setTimeout(function(){m.abort();j(m)},d.T));m.send(h);return m};var x;
x="XMLHttpRequest"in window?function(){return new XMLHttpRequest}:"ActiveXObject"in window?function(){return new ActiveXObject("Microsoft.XMLHTTP")}:void 0;u.a.s.create=x;u.b={};u.b.init=function(){u.b.o||(document.addEventListener("click",u.b.X,l),u.b.o=b)};u.b.p=function(){u.b.o&&(document.removeEventListener("click",u.b.X,l),u.b.o=l)};
u.b.X=function(a){u.debug.info("nav.handleClick",a);if(a.metaKey||a.altKey||a.ctrlKey||a.shiftKey)u.debug.warn("ignoring click with modifier key");else{var c=u.d.W(a.target,function(a){return u.d.k.has(a,u.config["link-class"])});if(c&&(!u.config["nolink-class"]||!u.d.W(a.target,function(a){return u.d.k.has(a,u.config["nolink-class"])})))if(c=c.href,!c||c==window.location.href)a.preventDefault();else{u.pubsub.q("navigate-started-callback",c);try{u.history.add(c),a.preventDefault()}catch(d){u.debug.error(">> error caught, ignoring click",
d)}}}};u.b.ma=function(a,c){var d=!(!c||!c["spf-back"]);u.debug.info("nav.handleHistory: ","url=",a,"state=",c);u.pubsub.q("navigate-history-callback",a);u.b.qa(a,d)};u.b.navigate=function(a){if(a&&a!=window.location.href){u.pubsub.q("navigate-started-callback",a);try{u.history.add(a)}catch(c){u.debug.error(">> error caught, redirecting",c),window.location.href=a}}};
u.b.qa=function(a,c){u.debug.info("nav.navigate",a,c);if(u.b.o){u.b.v&&(u.debug.warn("    >> aborting previous navigate",u.b.v),u.b.v.abort(),u.b.v=h);var d=u.b.V(a,function(a,d){u.b.v=h;u.b.D(d,c,"navigate-processed-callback")},function(a){u.b.v=h;window.location.href=a},"navigate-received-callback");u.b.v=d}else u.debug.error(">> nav not initialized")};
u.b.load=function(a,c,d){u.debug.info("nav.load",a);return u.b.V(a,function(a,d){u.b.D(d,l,"load-processed-callback");c&&c(a,d)},function(a){d&&d(a)},"load-received-callback")};
u.b.V=function(a,c,d,e){function f(d){try{var f="JSON"in window?JSON.parse(d.responseText):eval("("+d.responseText+")")}catch(sa){g();return}u.i.set(a,f,u.config["cache-lifetime"]);e&&u.pubsub.q(e,a,f);c&&c(a,f)}function g(){d&&d(a)}u.debug.info("nav.request",a);var j=a,k=u.config["url-identifier"]||"";k&&!u.h.contains(j,k)&&u.h.ka(k)&&(j=u.h.contains(j,"?")?j+k.replace("?","&"):j+k);if(k=u.i.get(a))u.debug.info("    >> cached response found",k),e&&u.pubsub.q(e,a,k),c&&c(a,k);else return u.debug.info("    >> fetching XHR"),
u.a.s.get(j,{T:u.config["request-timeout"],ia:f,onError:g,ja:g})};
u.b.D=function(a,c,d){function e(){0==f&&(u.a.scripts.execute(a.js,function(){d&&u.pubsub.q(d,a)}),f--)}u.debug.info("nav.process",a,c);u.a.styles.ga(a.css);a.title&&(document.title=a.title);var f=0,g=a.html||{};if(Object.keys)f=Object.keys(g).length;else for(var j in g)f++;for(j in g)if(g=document.getElementById(j)){var k=u.getKey(g);if(!u.b.aa||!u.d.k.has(g,u.config["transition-class"]))g.innerHTML=a.html[j],u.a.scripts.execute(a.html[j],function(){f--;e()});else{u.b.F(k,b);var m=[],r={};r.reverse=
!!c;r.u=g;r.ba=u.config["transition-current-child-class"];r.reverse?(r.S=u.config["transition-reverse-child-class"],r.M=u.config["transition-reverse-parent-class"]):(r.S=u.config["transition-forward-child-class"],r.M=u.config["transition-forward-parent-class"]);m.push([function(c,d){c.z=document.createElement("div");c.z.className=c.ba;u.d.da(c.u,c.z);c.A=document.createElement("div");c.A.className=c.S;c.A.innerHTML=a.html[c.u.id];c.reverse?u.d.fa(c.A,c.z):u.d.ea(c.A,c.z);d()},0]);m.push([function(a,
c){u.d.k.add(a.u,a.M);c()},0]);m.push([function(a,c){a.u.removeChild(a.z);u.d.k.remove(a.u,a.M);u.d.ca(a.A);c()},u.config["transition-duration"]]);m.push([function(c,d){u.a.scripts.execute(a.html[c.u.id],function(){f--;e();d()})},0]);u.b.R[k]={Q:0,P:m,data:r};u.b.F(k)}}e()};
u.b.F=function(a,c){var d=u.b.R;if(a in d)if(0<d[a].P.length){var e=d[a].P.shift();if(c)e[0](d[a].data,function(){u.b.F(a,c)});else d[a].Q=setTimeout(function(){e[0](d[a].data,function(){u.b.F(a,c)})},e[1])}else clearTimeout(d[a].Q),delete d[a]};u.b.o=l;u.b.R={};var da=u.b,y;a:{for(var ea=document.createElement("div"),z=["Webkit","Moz","Ms","O","Khtml"],A=0,fa=z.length;A<fa;A++)if(z[A]+"Transition"in ea.style){y=b;break a}y=l}da.aa=y;u.L={};u.L.init=function(a){var c=!!window.history.pushState;u.debug.info("main.init",c,a);a=a||{};for(var d in u.U){var e=d in a?a[d]:u.U[d];u.config[d]=e;c&&(e&&u.h.la(d))&&u.pubsub.G(d,e)}c&&(u.history.init(u.b.ma),u.b.init());return c};u.L.p=function(){u.b.p();u.history.p();u.pubsub.clear();u.config={}};u.init=u.L.init;u.p=u.L.p;u.navigate=u.b.navigate;u.load=u.b.load;u.D=u.b.D;window.spf=u.$?u:{init:u.init,dispose:u.p,navigate:u.navigate,load:u.load,process:u.D};var B=Array.prototype,ga=B.indexOf?function(a,c,d){return B.indexOf.call(a,c,d)}:function(a,c,d){d=d==h?0:0>d?Math.max(0,a.length+d):d;if(s(a))return!s(c)||1!=c.length?-1:a.indexOf(c,d);for(;d<a.length;d++)if(d in a&&a[d]===c)return d;return-1},C=B.forEach?function(a,c,d){B.forEach.call(a,c,d)}:function(a,c,d){for(var e=a.length,f=s(a)?a.split(""):a,g=0;g<e;g++)g in f&&c.call(d,f[g],g,a)};function ha(a,c,d){return 2>=arguments.length?B.slice.call(a,c):B.slice.call(a,c,d)};function D(){}D.prototype.w=l;D.prototype.p=function(){this.w||(this.w=b,this.N())};D.prototype.N=function(){this.O&&E.apply(h,this.O);if(this.C)for(;this.C.length;)this.C.shift()()};function E(a){for(var c=0,d=arguments.length;c<d;++c){var e=arguments[c],f=e,g=aa(f);"array"==g||"object"==g&&"number"==typeof f.length?E.apply(h,e):e&&"function"==typeof e.p&&e.p()}};function F(){this.g=[];this.e={}}function G(){}G.prototype=D.prototype;F.e=D.prototype;F.prototype=new G;n=F.prototype;n.Y=1;n.J=0;n.G=function(a,c,d){var e=this.e[a];e||(e=this.e[a]=[]);var f=this.Y;this.g[f]=a;this.g[f+1]=c;this.g[f+2]=d;this.Y=f+3;e.push(f);return f};n.ya=function(a,c,d){if(a=this.e[a]){var e=this.g,f;a:{f=function(a){return e[a+1]==c&&e[a+2]==d};for(var g=a.length,j=s(a)?a.split(""):a,k=0;k<g;k++)if(k in j&&f.call(void 0,j[k])){f=k;break a}f=-1}if(a=0>f?h:s(a)?a.charAt(f):a[f])return this.I(a)}return l};
n.I=function(a){if(0!=this.J)return this.j||(this.j=[]),this.j.push(a),l;var c=this.g[a];if(c){var d=this.e[c];if(d){var e=ga(d,a);0<=e&&B.splice.call(d,e,1)}delete this.g[a];delete this.g[a+1];delete this.g[a+2]}return!!c};n.q=function(a,c){var d=this.e[a];if(d){this.J++;for(var e=ha(arguments,1),f=0,g=d.length;f<g;f++){var j=d[f];this.g[j+1].apply(this.g[j+2],e)}this.J--;if(this.j&&0==this.J)for(;d=this.j.pop();)this.I(d);return 0!=f}return l};
n.clear=function(a){if(a){var c=this.e[a];c&&(C(c,this.I,this),delete this.e[a])}else this.g.length=0,this.e={}};n.N=function(){F.e.N.call(this);delete this.g;delete this.e;delete this.j};var H=window.yt&&window.yt.config_||{};t("yt.config_",H);var I=window.yt&&window.yt.tokens_||{};t("yt.tokens_",I);t("yt.globals_",window.yt&&window.yt.globals_||{});var J=window.yt&&window.yt.msgs_||{};t("yt.msgs_",J);var K=window.yt&&window.yt.timeouts_||[];t("yt.timeouts_",K);t("yt.intervals_",window.yt&&window.yt.intervals_||[]);function L(a,c){return a in H?H[a]:c}function M(a,c){var d=window.setTimeout(a,c);K.push(d)}
function N(a,c){if(1<c.length){var d=c[0];a[d]=c[1]}else{var e=c[0];for(d in e)a[d]=e[d]}};var ia=q("yt.pubsub.instance_")||new F;F.prototype.subscribe=F.prototype.G;F.prototype.unsubscribeByKey=F.prototype.I;F.prototype.publish=F.prototype.q;F.prototype.clear=F.prototype.clear;t("yt.pubsub.instance_",ia);function O(a){var c=q("yt.pubsub.instance_");return c?c.subscribe("init",function(){var c=arguments;M(function(){a.apply(p,c)},0)},void 0):0}function P(a,c){var d=q("yt.pubsub.instance_");d&&d.publish.apply(d,arguments)};function Q(){this.e=ba()}new Q;Q.prototype.set=function(a){this.e=a};Q.prototype.get=function(){return this.e};var R,S,T,U;function V(){return p.navigator?p.navigator.userAgent:h}U=T=S=R=l;var W;if(W=V()){var ja=p.navigator;R=0==W.indexOf("Opera");S=!R&&-1!=W.indexOf("MSIE");T=!R&&-1!=W.indexOf("WebKit");U=!R&&!T&&"Gecko"==ja.product}var ka=S,la=U,ma=T;var X;if(R&&p.opera){var Y=p.opera.version;"function"==typeof Y&&Y()}else la?X=/rv\:([^\);]+)(\)|;)/:ka?X=/MSIE\s+([^\);]+)(\)|;)/:ma&&(X=/WebKit\/(\S+)/),X&&X.exec(V());function na(){document.getElementById("content").className+=" loading ";var a=document.getElementById("progress");a||(a=document.createElement("div"),a.id="progress",a.innerHTML="<dt><dd>",document.body.appendChild(a));Z(60,900)}function oa(){Z(90,500);window.scroll(0,0);P("dispose");var a=document.getElementById("content");a.style.height=a.clientHeight+"px";$()}function pa(){Z(101,25);document.getElementById("content").style.height="";q("yt.timing.tick")("ol");P("init")}
function qa(){$(b);var a=document.getElementById("progress");a&&M(function(){a.parentNode.removeChild(a)},500)}function Z(a,c){var d=c||500,e=document.getElementById("progress");if(e){e.className="";var f=e.style;f.w=f.MozTransitionDuration=f.e=f.j=f.webkitTransitionDuration=d+"ms";M(function(){f.width=a+"%";M(function(){e.className="waiting"},d)},0)}}function $(a){function c(){d.className=d.className.replace(" loading ","")}var d=document.getElementById("content");a?c():M(c,50)};t("yt.setConfig",function(a){N(H,arguments)});t("yt.getConfig",L);t("yt.setMsg",function(a){N(J,arguments)});t("yt.setGoogMsg",function(a){N(J,arguments)});t("yt.setAjaxToken",function(a){N(I,arguments)});window.onload=function(){q("yt.timing.tick")("ol");P("init")};window.onunload=function(){P("dispose")};window.yt.spf&&(u.init({"nolink-class":"spf-nolink","navigate-history-callback":na,"navigate-received-callback":oa,"navigate-processed-callback":pa}),O(qa));
var ra=O(function(){u.a.scripts.load(L("WATCH_EXTRA_JS"),function(){q("ytbin.www.watch7.extra.setup")()});var a=ra,c=q("yt.pubsub.instance_");c&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[parseInt(a,10)]),C(a,function(a){c.unsubscribeByKey(a)}))});})();
